/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedConexaoWhatsappRouteImport } from './routes/_authenticated/conexao-whatsapp'
import { Route as AuthenticatedRecepcaoIndexRouteImport } from './routes/_authenticated/recepcao/index'
import { Route as AuthenticatedGestorIndexRouteImport } from './routes/_authenticated/gestor/index'
import { Route as AuthenticatedAgenciaIndexRouteImport } from './routes/_authenticated/agencia/index'
import { Route as AuthenticatedRecepcaoInternacoesRouteImport } from './routes/_authenticated/recepcao/internacoes'
import { Route as AuthenticatedRecepcaoExamesRouteImport } from './routes/_authenticated/recepcao/exames'
import { Route as AuthenticatedRecepcaoChatInternoRouteImport } from './routes/_authenticated/recepcao/chat-interno'
import { Route as AuthenticatedGestorUnidadesRouteImport } from './routes/_authenticated/gestor/unidades'
import { Route as AuthenticatedGestorRelatoriosRouteImport } from './routes/_authenticated/gestor/relatorios'
import { Route as AuthenticatedGestorChatInternoRouteImport } from './routes/_authenticated/gestor/chat-interno'
import { Route as AuthenticatedGestorAtendimentosRouteImport } from './routes/_authenticated/gestor/atendimentos'
import { Route as AuthenticatedAtendimentosIdRouteImport } from './routes/_authenticated/atendimentos.$id'
import { Route as AuthenticatedAgenciaUnidadesRouteImport } from './routes/_authenticated/agencia/unidades'
import { Route as AuthenticatedAgenciaRelatoriosRouteImport } from './routes/_authenticated/agencia/relatorios'
import { Route as AuthenticatedAgenciaRegrasIaRouteImport } from './routes/_authenticated/agencia/regras-ia'
import { Route as AuthenticatedAgenciaConfiguracoesIaRouteImport } from './routes/_authenticated/agencia/configuracoes-ia'
import { Route as AuthenticatedAgenciaClinicasRouteImport } from './routes/_authenticated/agencia/clinicas'
import { Route as AuthenticatedAgenciaBaseConhecimentoRouteImport } from './routes/_authenticated/agencia/base-conhecimento'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'
import { Route as ApiPublicWhatsappWebhookInstanceNameRouteImport } from './routes/api/public/whatsapp/webhook.$instanceName'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConexaoWhatsappRoute =
  AuthenticatedConexaoWhatsappRouteImport.update({
    id: '/conexao-whatsapp',
    path: '/conexao-whatsapp',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecepcaoIndexRoute =
  AuthenticatedRecepcaoIndexRouteImport.update({
    id: '/recepcao/',
    path: '/recepcao/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGestorIndexRoute =
  AuthenticatedGestorIndexRouteImport.update({
    id: '/gestor/',
    path: '/gestor/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgenciaIndexRoute =
  AuthenticatedAgenciaIndexRouteImport.update({
    id: '/agencia/',
    path: '/agencia/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecepcaoInternacoesRoute =
  AuthenticatedRecepcaoInternacoesRouteImport.update({
    id: '/recepcao/internacoes',
    path: '/recepcao/internacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecepcaoExamesRoute =
  AuthenticatedRecepcaoExamesRouteImport.update({
    id: '/recepcao/exames',
    path: '/recepcao/exames',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecepcaoChatInternoRoute =
  AuthenticatedRecepcaoChatInternoRouteImport.update({
    id: '/recepcao/chat-interno',
    path: '/recepcao/chat-interno',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGestorUnidadesRoute =
  AuthenticatedGestorUnidadesRouteImport.update({
    id: '/gestor/unidades',
    path: '/gestor/unidades',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGestorRelatoriosRoute =
  AuthenticatedGestorRelatoriosRouteImport.update({
    id: '/gestor/relatorios',
    path: '/gestor/relatorios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGestorChatInternoRoute =
  AuthenticatedGestorChatInternoRouteImport.update({
    id: '/gestor/chat-interno',
    path: '/gestor/chat-interno',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGestorAtendimentosRoute =
  AuthenticatedGestorAtendimentosRouteImport.update({
    id: '/gestor/atendimentos',
    path: '/gestor/atendimentos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAtendimentosIdRoute =
  AuthenticatedAtendimentosIdRouteImport.update({
    id: '/atendimentos/$id',
    path: '/atendimentos/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgenciaUnidadesRoute =
  AuthenticatedAgenciaUnidadesRouteImport.update({
    id: '/agencia/unidades',
    path: '/agencia/unidades',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgenciaRelatoriosRoute =
  AuthenticatedAgenciaRelatoriosRouteImport.update({
    id: '/agencia/relatorios',
    path: '/agencia/relatorios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgenciaRegrasIaRoute =
  AuthenticatedAgenciaRegrasIaRouteImport.update({
    id: '/agencia/regras-ia',
    path: '/agencia/regras-ia',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgenciaConfiguracoesIaRoute =
  AuthenticatedAgenciaConfiguracoesIaRouteImport.update({
    id: '/agencia/configuracoes-ia',
    path: '/agencia/configuracoes-ia',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgenciaClinicasRoute =
  AuthenticatedAgenciaClinicasRouteImport.update({
    id: '/agencia/clinicas',
    path: '/agencia/clinicas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgenciaBaseConhecimentoRoute =
  AuthenticatedAgenciaBaseConhecimentoRouteImport.update({
    id: '/agencia/base-conhecimento',
    path: '/agencia/base-conhecimento',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappWebhookInstanceNameRoute =
  ApiPublicWhatsappWebhookInstanceNameRouteImport.update({
    id: '/$instanceName',
    path: '/$instanceName',
    getParentRoute: () => ApiPublicWhatsappWebhookRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/conexao-whatsapp': typeof AuthenticatedConexaoWhatsappRoute
  '/agencia/base-conhecimento': typeof AuthenticatedAgenciaBaseConhecimentoRoute
  '/agencia/clinicas': typeof AuthenticatedAgenciaClinicasRoute
  '/agencia/configuracoes-ia': typeof AuthenticatedAgenciaConfiguracoesIaRoute
  '/agencia/regras-ia': typeof AuthenticatedAgenciaRegrasIaRoute
  '/agencia/relatorios': typeof AuthenticatedAgenciaRelatoriosRoute
  '/agencia/unidades': typeof AuthenticatedAgenciaUnidadesRoute
  '/atendimentos/$id': typeof AuthenticatedAtendimentosIdRoute
  '/gestor/atendimentos': typeof AuthenticatedGestorAtendimentosRoute
  '/gestor/chat-interno': typeof AuthenticatedGestorChatInternoRoute
  '/gestor/relatorios': typeof AuthenticatedGestorRelatoriosRoute
  '/gestor/unidades': typeof AuthenticatedGestorUnidadesRoute
  '/recepcao/chat-interno': typeof AuthenticatedRecepcaoChatInternoRoute
  '/recepcao/exames': typeof AuthenticatedRecepcaoExamesRoute
  '/recepcao/internacoes': typeof AuthenticatedRecepcaoInternacoesRoute
  '/agencia/': typeof AuthenticatedAgenciaIndexRoute
  '/gestor/': typeof AuthenticatedGestorIndexRoute
  '/recepcao/': typeof AuthenticatedRecepcaoIndexRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRouteWithChildren
  '/api/public/whatsapp/webhook/$instanceName': typeof ApiPublicWhatsappWebhookInstanceNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/conexao-whatsapp': typeof AuthenticatedConexaoWhatsappRoute
  '/agencia/base-conhecimento': typeof AuthenticatedAgenciaBaseConhecimentoRoute
  '/agencia/clinicas': typeof AuthenticatedAgenciaClinicasRoute
  '/agencia/configuracoes-ia': typeof AuthenticatedAgenciaConfiguracoesIaRoute
  '/agencia/regras-ia': typeof AuthenticatedAgenciaRegrasIaRoute
  '/agencia/relatorios': typeof AuthenticatedAgenciaRelatoriosRoute
  '/agencia/unidades': typeof AuthenticatedAgenciaUnidadesRoute
  '/atendimentos/$id': typeof AuthenticatedAtendimentosIdRoute
  '/gestor/atendimentos': typeof AuthenticatedGestorAtendimentosRoute
  '/gestor/chat-interno': typeof AuthenticatedGestorChatInternoRoute
  '/gestor/relatorios': typeof AuthenticatedGestorRelatoriosRoute
  '/gestor/unidades': typeof AuthenticatedGestorUnidadesRoute
  '/recepcao/chat-interno': typeof AuthenticatedRecepcaoChatInternoRoute
  '/recepcao/exames': typeof AuthenticatedRecepcaoExamesRoute
  '/recepcao/internacoes': typeof AuthenticatedRecepcaoInternacoesRoute
  '/agencia': typeof AuthenticatedAgenciaIndexRoute
  '/gestor': typeof AuthenticatedGestorIndexRoute
  '/recepcao': typeof AuthenticatedRecepcaoIndexRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRouteWithChildren
  '/api/public/whatsapp/webhook/$instanceName': typeof ApiPublicWhatsappWebhookInstanceNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/conexao-whatsapp': typeof AuthenticatedConexaoWhatsappRoute
  '/_authenticated/agencia/base-conhecimento': typeof AuthenticatedAgenciaBaseConhecimentoRoute
  '/_authenticated/agencia/clinicas': typeof AuthenticatedAgenciaClinicasRoute
  '/_authenticated/agencia/configuracoes-ia': typeof AuthenticatedAgenciaConfiguracoesIaRoute
  '/_authenticated/agencia/regras-ia': typeof AuthenticatedAgenciaRegrasIaRoute
  '/_authenticated/agencia/relatorios': typeof AuthenticatedAgenciaRelatoriosRoute
  '/_authenticated/agencia/unidades': typeof AuthenticatedAgenciaUnidadesRoute
  '/_authenticated/atendimentos/$id': typeof AuthenticatedAtendimentosIdRoute
  '/_authenticated/gestor/atendimentos': typeof AuthenticatedGestorAtendimentosRoute
  '/_authenticated/gestor/chat-interno': typeof AuthenticatedGestorChatInternoRoute
  '/_authenticated/gestor/relatorios': typeof AuthenticatedGestorRelatoriosRoute
  '/_authenticated/gestor/unidades': typeof AuthenticatedGestorUnidadesRoute
  '/_authenticated/recepcao/chat-interno': typeof AuthenticatedRecepcaoChatInternoRoute
  '/_authenticated/recepcao/exames': typeof AuthenticatedRecepcaoExamesRoute
  '/_authenticated/recepcao/internacoes': typeof AuthenticatedRecepcaoInternacoesRoute
  '/_authenticated/agencia/': typeof AuthenticatedAgenciaIndexRoute
  '/_authenticated/gestor/': typeof AuthenticatedGestorIndexRoute
  '/_authenticated/recepcao/': typeof AuthenticatedRecepcaoIndexRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRouteWithChildren
  '/api/public/whatsapp/webhook/$instanceName': typeof ApiPublicWhatsappWebhookInstanceNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/conexao-whatsapp'
    | '/agencia/base-conhecimento'
    | '/agencia/clinicas'
    | '/agencia/configuracoes-ia'
    | '/agencia/regras-ia'
    | '/agencia/relatorios'
    | '/agencia/unidades'
    | '/atendimentos/$id'
    | '/gestor/atendimentos'
    | '/gestor/chat-interno'
    | '/gestor/relatorios'
    | '/gestor/unidades'
    | '/recepcao/chat-interno'
    | '/recepcao/exames'
    | '/recepcao/internacoes'
    | '/agencia/'
    | '/gestor/'
    | '/recepcao/'
    | '/api/public/whatsapp/webhook'
    | '/api/public/whatsapp/webhook/$instanceName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/conexao-whatsapp'
    | '/agencia/base-conhecimento'
    | '/agencia/clinicas'
    | '/agencia/configuracoes-ia'
    | '/agencia/regras-ia'
    | '/agencia/relatorios'
    | '/agencia/unidades'
    | '/atendimentos/$id'
    | '/gestor/atendimentos'
    | '/gestor/chat-interno'
    | '/gestor/relatorios'
    | '/gestor/unidades'
    | '/recepcao/chat-interno'
    | '/recepcao/exames'
    | '/recepcao/internacoes'
    | '/agencia'
    | '/gestor'
    | '/recepcao'
    | '/api/public/whatsapp/webhook'
    | '/api/public/whatsapp/webhook/$instanceName'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/conexao-whatsapp'
    | '/_authenticated/agencia/base-conhecimento'
    | '/_authenticated/agencia/clinicas'
    | '/_authenticated/agencia/configuracoes-ia'
    | '/_authenticated/agencia/regras-ia'
    | '/_authenticated/agencia/relatorios'
    | '/_authenticated/agencia/unidades'
    | '/_authenticated/atendimentos/$id'
    | '/_authenticated/gestor/atendimentos'
    | '/_authenticated/gestor/chat-interno'
    | '/_authenticated/gestor/relatorios'
    | '/_authenticated/gestor/unidades'
    | '/_authenticated/recepcao/chat-interno'
    | '/_authenticated/recepcao/exames'
    | '/_authenticated/recepcao/internacoes'
    | '/_authenticated/agencia/'
    | '/_authenticated/gestor/'
    | '/_authenticated/recepcao/'
    | '/api/public/whatsapp/webhook'
    | '/api/public/whatsapp/webhook/$instanceName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/conexao-whatsapp': {
      id: '/_authenticated/conexao-whatsapp'
      path: '/conexao-whatsapp'
      fullPath: '/conexao-whatsapp'
      preLoaderRoute: typeof AuthenticatedConexaoWhatsappRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recepcao/': {
      id: '/_authenticated/recepcao/'
      path: '/recepcao'
      fullPath: '/recepcao/'
      preLoaderRoute: typeof AuthenticatedRecepcaoIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gestor/': {
      id: '/_authenticated/gestor/'
      path: '/gestor'
      fullPath: '/gestor/'
      preLoaderRoute: typeof AuthenticatedGestorIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agencia/': {
      id: '/_authenticated/agencia/'
      path: '/agencia'
      fullPath: '/agencia/'
      preLoaderRoute: typeof AuthenticatedAgenciaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recepcao/internacoes': {
      id: '/_authenticated/recepcao/internacoes'
      path: '/recepcao/internacoes'
      fullPath: '/recepcao/internacoes'
      preLoaderRoute: typeof AuthenticatedRecepcaoInternacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recepcao/exames': {
      id: '/_authenticated/recepcao/exames'
      path: '/recepcao/exames'
      fullPath: '/recepcao/exames'
      preLoaderRoute: typeof AuthenticatedRecepcaoExamesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recepcao/chat-interno': {
      id: '/_authenticated/recepcao/chat-interno'
      path: '/recepcao/chat-interno'
      fullPath: '/recepcao/chat-interno'
      preLoaderRoute: typeof AuthenticatedRecepcaoChatInternoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gestor/unidades': {
      id: '/_authenticated/gestor/unidades'
      path: '/gestor/unidades'
      fullPath: '/gestor/unidades'
      preLoaderRoute: typeof AuthenticatedGestorUnidadesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gestor/relatorios': {
      id: '/_authenticated/gestor/relatorios'
      path: '/gestor/relatorios'
      fullPath: '/gestor/relatorios'
      preLoaderRoute: typeof AuthenticatedGestorRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gestor/chat-interno': {
      id: '/_authenticated/gestor/chat-interno'
      path: '/gestor/chat-interno'
      fullPath: '/gestor/chat-interno'
      preLoaderRoute: typeof AuthenticatedGestorChatInternoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gestor/atendimentos': {
      id: '/_authenticated/gestor/atendimentos'
      path: '/gestor/atendimentos'
      fullPath: '/gestor/atendimentos'
      preLoaderRoute: typeof AuthenticatedGestorAtendimentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/atendimentos/$id': {
      id: '/_authenticated/atendimentos/$id'
      path: '/atendimentos/$id'
      fullPath: '/atendimentos/$id'
      preLoaderRoute: typeof AuthenticatedAtendimentosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agencia/unidades': {
      id: '/_authenticated/agencia/unidades'
      path: '/agencia/unidades'
      fullPath: '/agencia/unidades'
      preLoaderRoute: typeof AuthenticatedAgenciaUnidadesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agencia/relatorios': {
      id: '/_authenticated/agencia/relatorios'
      path: '/agencia/relatorios'
      fullPath: '/agencia/relatorios'
      preLoaderRoute: typeof AuthenticatedAgenciaRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agencia/regras-ia': {
      id: '/_authenticated/agencia/regras-ia'
      path: '/agencia/regras-ia'
      fullPath: '/agencia/regras-ia'
      preLoaderRoute: typeof AuthenticatedAgenciaRegrasIaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agencia/configuracoes-ia': {
      id: '/_authenticated/agencia/configuracoes-ia'
      path: '/agencia/configuracoes-ia'
      fullPath: '/agencia/configuracoes-ia'
      preLoaderRoute: typeof AuthenticatedAgenciaConfiguracoesIaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agencia/clinicas': {
      id: '/_authenticated/agencia/clinicas'
      path: '/agencia/clinicas'
      fullPath: '/agencia/clinicas'
      preLoaderRoute: typeof AuthenticatedAgenciaClinicasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agencia/base-conhecimento': {
      id: '/_authenticated/agencia/base-conhecimento'
      path: '/agencia/base-conhecimento'
      fullPath: '/agencia/base-conhecimento'
      preLoaderRoute: typeof AuthenticatedAgenciaBaseConhecimentoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook/$instanceName': {
      id: '/api/public/whatsapp/webhook/$instanceName'
      path: '/$instanceName'
      fullPath: '/api/public/whatsapp/webhook/$instanceName'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookInstanceNameRouteImport
      parentRoute: typeof ApiPublicWhatsappWebhookRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedConexaoWhatsappRoute: typeof AuthenticatedConexaoWhatsappRoute
  AuthenticatedAgenciaBaseConhecimentoRoute: typeof AuthenticatedAgenciaBaseConhecimentoRoute
  AuthenticatedAgenciaClinicasRoute: typeof AuthenticatedAgenciaClinicasRoute
  AuthenticatedAgenciaConfiguracoesIaRoute: typeof AuthenticatedAgenciaConfiguracoesIaRoute
  AuthenticatedAgenciaRegrasIaRoute: typeof AuthenticatedAgenciaRegrasIaRoute
  AuthenticatedAgenciaRelatoriosRoute: typeof AuthenticatedAgenciaRelatoriosRoute
  AuthenticatedAgenciaUnidadesRoute: typeof AuthenticatedAgenciaUnidadesRoute
  AuthenticatedAtendimentosIdRoute: typeof AuthenticatedAtendimentosIdRoute
  AuthenticatedGestorAtendimentosRoute: typeof AuthenticatedGestorAtendimentosRoute
  AuthenticatedGestorChatInternoRoute: typeof AuthenticatedGestorChatInternoRoute
  AuthenticatedGestorRelatoriosRoute: typeof AuthenticatedGestorRelatoriosRoute
  AuthenticatedGestorUnidadesRoute: typeof AuthenticatedGestorUnidadesRoute
  AuthenticatedRecepcaoChatInternoRoute: typeof AuthenticatedRecepcaoChatInternoRoute
  AuthenticatedRecepcaoExamesRoute: typeof AuthenticatedRecepcaoExamesRoute
  AuthenticatedRecepcaoInternacoesRoute: typeof AuthenticatedRecepcaoInternacoesRoute
  AuthenticatedAgenciaIndexRoute: typeof AuthenticatedAgenciaIndexRoute
  AuthenticatedGestorIndexRoute: typeof AuthenticatedGestorIndexRoute
  AuthenticatedRecepcaoIndexRoute: typeof AuthenticatedRecepcaoIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConexaoWhatsappRoute: AuthenticatedConexaoWhatsappRoute,
  AuthenticatedAgenciaBaseConhecimentoRoute:
    AuthenticatedAgenciaBaseConhecimentoRoute,
  AuthenticatedAgenciaClinicasRoute: AuthenticatedAgenciaClinicasRoute,
  AuthenticatedAgenciaConfiguracoesIaRoute:
    AuthenticatedAgenciaConfiguracoesIaRoute,
  AuthenticatedAgenciaRegrasIaRoute: AuthenticatedAgenciaRegrasIaRoute,
  AuthenticatedAgenciaRelatoriosRoute: AuthenticatedAgenciaRelatoriosRoute,
  AuthenticatedAgenciaUnidadesRoute: AuthenticatedAgenciaUnidadesRoute,
  AuthenticatedAtendimentosIdRoute: AuthenticatedAtendimentosIdRoute,
  AuthenticatedGestorAtendimentosRoute: AuthenticatedGestorAtendimentosRoute,
  AuthenticatedGestorChatInternoRoute: AuthenticatedGestorChatInternoRoute,
  AuthenticatedGestorRelatoriosRoute: AuthenticatedGestorRelatoriosRoute,
  AuthenticatedGestorUnidadesRoute: AuthenticatedGestorUnidadesRoute,
  AuthenticatedRecepcaoChatInternoRoute: AuthenticatedRecepcaoChatInternoRoute,
  AuthenticatedRecepcaoExamesRoute: AuthenticatedRecepcaoExamesRoute,
  AuthenticatedRecepcaoInternacoesRoute: AuthenticatedRecepcaoInternacoesRoute,
  AuthenticatedAgenciaIndexRoute: AuthenticatedAgenciaIndexRoute,
  AuthenticatedGestorIndexRoute: AuthenticatedGestorIndexRoute,
  AuthenticatedRecepcaoIndexRoute: AuthenticatedRecepcaoIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiPublicWhatsappWebhookRouteChildren {
  ApiPublicWhatsappWebhookInstanceNameRoute: typeof ApiPublicWhatsappWebhookInstanceNameRoute
}

const ApiPublicWhatsappWebhookRouteChildren: ApiPublicWhatsappWebhookRouteChildren =
  {
    ApiPublicWhatsappWebhookInstanceNameRoute:
      ApiPublicWhatsappWebhookInstanceNameRoute,
  }

const ApiPublicWhatsappWebhookRouteWithChildren =
  ApiPublicWhatsappWebhookRoute._addFileChildren(
    ApiPublicWhatsappWebhookRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
